kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: hello-spring-cloud-kubernetes-read
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]