management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always  
  endpoints:
      web:
        exposure:
            include: '*'

spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
