apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-spring-kubernetes
  name: hello-spring-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-kubernetes
  template:
    metadata:
      labels:
        app: hello-spring-kubernetes
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: eu.gcr.io/pa-afa-kubernetes/hello-spring-kubernetes:latest
          name: hello-spring-kubernetes
          imagePullPolicy: Always
          env:
            - name: HELLO_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-spring-kubernetes
                  key: hello.message
            - name: HELLO_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: hello-spring-kubernetes
                  key: hello.prefix
            - name: USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hello-spring-kubernetes
                  key: user.username
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-spring-kubernetes
                  key: user.password
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hello-spring-kubernetes
                  key: admin.username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-spring-kubernetes
                  key: admin.password
          resources:
            limits:
              memory: "1024Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5    
      restartPolicy: Always
